### ISSUE TITLE
g_variant_new_string: assertion 'string != NULL' failed

### ISSUE THREAD

**Issue by mcatanzaro** [endlessm/eos-event-recorder-daemon#292]
Using commit ab67c9347cdc52be6a8f63d8bb4e9c43584d3a85 on Fedora 38, when trying to upload metrics I see `g_variant_new_string: assertion 'string != NULL' failed`. I got this backtrace:

```
#0  g_logv
    (log_domain=0x7f46a9ca20be "GLib", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7ffcf17b3120) at ../glib/gmessages.c:1422
#1  0x00007f46a9c45fb3 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>)
    at ../glib/gmessages.c:1460
#2  0x00007f46a9c85f82 in g_variant_new_string (string=string@entry=0x0) at ../glib/gvariant.c:1269
#3  0x00007f46a9c87578 in g_variant_valist_new_nnp (str=str@entry=0x7ffcf17b3328, ptr=0x0) at ../glib/gvariant.c:4870
#4  0x00007f46a9c87b5e in g_variant_valist_new_leaf (app=0x7ffcf17b3350, str=0x7ffcf17b3328)
    at ../glib/gvariant.c:5065
#5  0x00007f46a9c879f3 in g_variant_valist_new (str=str@entry=0x7ffcf17b3328, app=app@entry=0x7ffcf17b3350)
    at ../glib/gvariant.c:5299
#6  0x00007f46a9c88009 in g_variant_new_va (format_string=<optimized out>, 
    format_string@entry=0x5623b78a3730 "(xxs@a{ss}ya(aysxmv)a(ayssumv))", endptr=endptr@entry=0x0, app=app@entry=0x7ffcf17b3350) at ../glib/gvariant.c:5475
#7  0x00007f46a9c8814e in g_variant_new
    (format_string=format_string@entry=0x5623b78a3730 "(xxs@a{ss}ya(aysxmv)a(ayssumv))") at ../glib/gvariant.c:5410
#8  0x00005623b789f40c in create_request_body
    (error=0x7ffcf17b34d8, num_buffer_events=<synthetic pointer>, num_stored_events=<synthetic pointer>, token=0x7ffcf17b34d0, max_bytes=<optimized out>, self=0x5623b8a66cb0) at ../daemon/emer-daemon.c:779
#9  handle_network_monitor_can_reach (network_monitor=<optimized out>, result=<optimized out>, self=0x5623b8a66cb0)
    at ../daemon/emer-daemon.c:833
#10 0x00007f46a9ac352c in g_task_return_now (task=0x5623b8ac9210) at ../gio/gtask.c:1309
#11 0x00007f46a9ac72e3 in g_task_return (type=<optimized out>, task=0x5623b8ac9210) at ../gio/gtask.c:1378
#12 g_task_return (task=0x5623b8ac9210, type=<optimized out>) at ../gio/gtask.c:1335
#13 0x00007f46a9a9f3c2 in can_reach_async_got_address
    (object=0x5623b8aca680, result=<optimized out>, user_data=0x5623b8ac9210) at ../gio/gnetworkmonitorbase.c:298
#14 0x00007f46a9ac352c in g_task_return_now (task=0x5623b8ae54f0) at ../gio/gtask.c:1309
#15 0x00007f46a9ac72e3 in g_task_return (type=<optimized out>, task=0x5623b8ae54f0) at ../gio/gtask.c:1378
#16 g_task_return (task=0x5623b8ae54f0, type=<optimized out>) at ../gio/gtask.c:1335
#17 0x00007f46a9aa9fd8 in return_result (task=0x5623b8ae54f0) at ../gio/gproxyaddressenumerator.c:423
#18 0x00007f46a9ac352c in g_task_return_now (task=0x5623b8ae5790) at ../gio/gtask.c:1309
#19 0x00007f46a9ac72e3 in g_task_return (type=<optimized out>, task=0x5623b8ae5790) at ../gio/gtask.c:1378
#20 g_task_return (task=0x5623b8ae5790, type=<optimized out>) at ../gio/gtask.c:1335
#21 0x00007f46a9a9e672 in complete_queued_task (error=0x0, task=0x5623b8ae5790, addr_enum=0x5623b8ae5720)
    at ../gio/gnetworkaddress.c:925
#22 got_ipv6_addresses (source_object=<optimized out>, result=<optimized out>, user_data=0x5623b8ae5720)
    at ../gio/gnetworkaddress.c:999
#23 0x00007f46a9ac352c in g_task_return_now (task=0x5623b8ae5850) at ../gio/gtask.c:1309
#24 0x00007f46a9ac3565 in complete_in_idle_cb (task=task@entry=0x5623b8ae5850) at ../gio/gtask.c:1323
#25 0x00007f46a9c3c9ed in g_idle_dispatch
    (source=0x7f4690008580, callback=0x7f46a9ac3550 <complete_in_idle_cb>, user_data=0x5623b8ae5850)
    at ../glib/gmain.c:6163
#26 0x00007f46a9c40788 in g_main_dispatch (context=0x5623b8a6d7a0) at ../glib/gmain.c:3460
#27 g_main_context_dispatch (context=0x5623b8a6d7a0) at ../glib/gmain.c:4200
#28 0x00007f46a9c9edd8 in g_main_context_iterate.isra.0
    (context=0x5623b8a6d7a0, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4276
#29 0x00007f46a9c3fe8f in g_main_loop_run (loop=0x5623b8ab42f0) at ../glib/gmain.c:4479
#30 0x00005623b78918fe in main (argc=<optimized out>, argv=<optimized out>) at ../daemon/emer-main.c:468
```

I believe the problem is that `create_request_body()` is not prepared for `emer_image_id_provider_get_version()` to return NULL (which will always happen except on Endless OS).

**Comment by Kurt-von-Laven** [comment]
I feel simultaneously thrilled to see eos-event-recorder-daemon being used beyond Endless OS and guilty since I'm sure I must have liberally sprinkled the assumption of running on Endless OS all over the place.

**Comment by mcatanzaro** [comment]
>  guilty since I'm sure I must have liberally sprinkled the assumption of running on Endless OS all over the place.

We'll untangle it. ;)
